#!/usr/bin/env node
// Sync OpenCode config + data to/from a GitHub private repo.
// Cross-platform (macOS / Windows / Linux).
//
// Commands:
//   push     Push config + non-session data
//   pull     Pull config + non-session data
//   status   Show sync status
//
// Session sync (db + storage + tool-output) has been moved to a
// standalone script: ~/.config/opencode/scripts/sync-sessions.js
// That script must run OUTSIDE OpenCode to avoid SQLite corruption.
//
// Push maintains "local-consistent" semantics:
// deletions on local side are propagated to remote (not additive-only).
//
// Syncs four directories into one git repo:
//   ~/.config/opencode/     → repo root (config, skills, commands, etc.)
//   ~/.local/share/opencode → repo _data/ (auth, sync-state, sessions)
//   ~/.local/state/opencode → repo _state/ (frecency, kv, model, etc.)
//   ~/.agents/skills/       → repo _agents/ (skills CLI global installs)
//
// Large binary files (*.db) are tracked via Git LFS.
//
// Environment overrides (for testing):
//   SYNC_CONFIG_ROOT  — override config directory
//   SYNC_DATA_ROOT    — override data directory
//   SYNC_STATE_ROOT   — override state directory
//   SYNC_AGENTS_ROOT  — override agents/skills directory
//   SYNC_REMOTE_URL   — override git remote URL
//   SYNC_SKIP_LFS     — skip LFS setup (for tests without git-lfs)

const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const { execSync } = require("node:child_process");
const { c, success, error, warn, step, note, formatStats, formatDiffStats, completionBanner, upToDateBanner } = require("./ui");

// ── Constants ────────────────────────────────────────────────────────

const BRANCH = "main";

const DEFAULT_GITIGNORE = `# Runtime / generated
node_modules/
/package.json
/package-lock.json
bun.lock

# OS files
.DS_Store
Thumbs.db
desktop.ini

# Empty dirs (runtime-generated by plugins)
plugin/

# Data dir: skip binaries and logs (large, machine-specific)
_data/bin/
_data/log/
# SQLite WAL/SHM — we checkpoint before push, only track the main db
_data/opencode.db-shm
_data/opencode.db-wal
.gitignore

# Machine-specific identity (not synced)
.device-identity.json
`;

const DEFAULT_GITATTRIBUTES = `# Normalize line endings across platforms
* text=auto

# Git LFS — large binary files
_data/opencode.db filter=lfs diff=lfs merge=lfs -text
`;

// Non-session data files (synced by push/pull)
const CONFIG_DATA_FILES = [
  "auth.json",
  "sync-state.json",
];
// Non-session data directories (synced by push/pull)
const CONFIG_DATA_DIRS = [
  // storage/project and storage/migration are non-session data
];

// ── Helpers ──────────────────────────────────────────────────────────

function getConfigRoot() {
  if (process.env.SYNC_CONFIG_ROOT) return process.env.SYNC_CONFIG_ROOT;
  const xdg = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config");
  return path.join(xdg, "opencode");
}

function getDataRoot() {
  if (process.env.SYNC_DATA_ROOT) return process.env.SYNC_DATA_ROOT;
  const xdgData = process.env.XDG_DATA_HOME || path.join(os.homedir(), ".local", "share");
  return path.join(xdgData, "opencode");
}

function getStateRoot() {
  if (process.env.SYNC_STATE_ROOT) return process.env.SYNC_STATE_ROOT;
  const xdgState = process.env.XDG_STATE_HOME || path.join(os.homedir(), ".local", "state");
  return path.join(xdgState, "opencode");
}

function getAgentsRoot() {
  if (process.env.SYNC_AGENTS_ROOT) return process.env.SYNC_AGENTS_ROOT;
  return path.join(os.homedir(), ".agents", "skills");
}

function getRemoteUrl() {
  const url = process.env.SYNC_REMOTE_URL;
  if (!url) {
    error("SYNC_REMOTE_URL environment variable is not set.");
    console.error("   Set it to your GitHub repo URL, e.g.:");
    console.error("   export SYNC_REMOTE_URL=\"https://github.com/user/repo.git\"");
    process.exit(1);
  }
  return url;
}

function skipLfs() {
  return process.env.SYNC_SKIP_LFS === "1";
}

function git(args, opts = {}) {
  const cwd = opts.cwd || getConfigRoot();
  try {
    return { ok: true, out: execSync(`git ${args}`, {
      cwd, encoding: "utf8", stdio: "pipe",
      env: { ...process.env, GIT_TERMINAL_PROMPT: "0" },
    }).trim() };
  } catch (e) {
    return { ok: false, out: (e.stdout || "").trim(), err: (e.stderr || "").trim(), code: e.status };
  }
}

function isGitRepo(dir) {
  return fs.existsSync(path.join(dir, ".git"));
}

function ensureFile(filePath, content) {
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content);
    return true;
  }
  return false;
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function timestamp() {
  return new Date().toISOString().replace(/T/, " ").replace(/\..+/, "");
}

function commitMessage(prefix = "sync") {
  const host = os.hostname();
  const plat = process.platform === "win32" ? "windows" : process.platform === "darwin" ? "mac" : process.platform;
  return `${prefix}: ${timestamp()} from ${host} (${plat})`;
}

// ── Nested .git cleanup ─────────────────────────────────────────────
// npx skills can clone entire repos into skills dirs, leaving nested
// .git/ folders. Git records these as gitlink submodule pointers instead
// of tracking the actual files, making them invisible to other machines.
// This function removes nested .git dirs so all files get committed normally.

function removeNestedGitDirs(...dirs) {
  let removed = 0;
  for (const dir of dirs) {
    if (!fs.existsSync(dir)) continue;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const nestedGit = path.join(dir, entry.name, ".git");
      if (fs.existsSync(nestedGit)) {
        fs.rmSync(nestedGit, { recursive: true, force: true });
        removed++;
      }
    }
  }
  return removed;
}

// ── Copy helpers ─────────────────────────────────────────────────────

function copyFileIfExists(src, dst) {
  if (fs.existsSync(src)) {
    ensureDir(path.dirname(dst));
    fs.copyFileSync(src, dst);
    return true;
  }
  return false;
}

function copyDirRecursive(src, dst) {
  if (!fs.existsSync(src)) return 0;
  ensureDir(dst);
  let count = 0;
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const dstPath = path.join(dst, entry.name);
    if (entry.isDirectory()) {
      count += copyDirRecursive(srcPath, dstPath);
    } else {
      fs.copyFileSync(srcPath, dstPath);
      count++;
    }
  }
  return count;
}

// Remove a directory and all its contents
function rmDirRecursive(dir) {
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

// Remove a single file if it exists
function rmFileIfExists(filePath) {
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
}

// ── Data staging (copy external dirs into/out of repo) ───────────────

/**
 * Stage non-session data into repo (_data/ for auth/sync-state, _state/ for state dir).
 * Cleans destination dirs before copying to maintain local-consistent semantics.
 */
function stageConfigDataIn(root) {
  const dataRoot = getDataRoot();
  const stateRoot = getStateRoot();
  const agentsRoot = getAgentsRoot();
  const repoData = path.join(root, "_data");
  const repoState = path.join(root, "_state");
  const repoAgents = path.join(root, "_agents");

  // Clean nested .git dirs from skills before staging
  const skillsDir = path.join(root, "skills");
  removeNestedGitDirs(skillsDir, agentsRoot);

  let fileCount = 0;

  // Copy non-session data files
  ensureDir(repoData);
  for (const file of CONFIG_DATA_FILES) {
    if (copyFileIfExists(path.join(dataRoot, file), path.join(repoData, file))) {
      fileCount++;
    }
  }

  // Copy non-session data directories (currently none, but extensible)
  for (const dir of CONFIG_DATA_DIRS) {
    const src = path.join(dataRoot, dir);
    if (fs.existsSync(src)) {
      rmDirRecursive(path.join(repoData, dir));
      fileCount += copyDirRecursive(src, path.join(repoData, dir));
    }
  }

  // Copy entire state directory (clean first for local-consistent)
  if (fs.existsSync(stateRoot)) {
    rmDirRecursive(repoState);
    fileCount += copyDirRecursive(stateRoot, repoState);
  }

  // Copy ~/.agents/skills/ (skills CLI global installs)
  if (fs.existsSync(agentsRoot)) {
    rmDirRecursive(repoAgents);
    fileCount += copyDirRecursive(agentsRoot, repoAgents);
  }

  // Copy ~/.agents/.skill-lock.json (skills CLI install registry)
  const agentsParent = path.dirname(agentsRoot);
  const lockFile = path.join(agentsParent, ".skill-lock.json");
  if (copyFileIfExists(lockFile, path.join(repoAgents, ".skill-lock.json"))) {
    fileCount++;
  }

  // staging is internal — no output needed
}

/**
 * Restore non-session data from repo to their real locations.
 * Cleans destination dirs before copying to maintain local-consistent semantics.
 */
function stageConfigDataOut(root) {
  const dataRoot = getDataRoot();
  const stateRoot = getStateRoot();
  const agentsRoot = getAgentsRoot();
  const repoData = path.join(root, "_data");
  const repoState = path.join(root, "_state");
  const repoAgents = path.join(root, "_agents");

  let fileCount = 0;

  // Restore non-session data files
  ensureDir(dataRoot);
  for (const file of CONFIG_DATA_FILES) {
    if (copyFileIfExists(path.join(repoData, file), path.join(dataRoot, file))) {
      fileCount++;
    }
  }

  // Restore non-session data directories
  for (const dir of CONFIG_DATA_DIRS) {
    const src = path.join(repoData, dir);
    if (fs.existsSync(src)) {
      rmDirRecursive(path.join(dataRoot, dir));
      fileCount += copyDirRecursive(src, path.join(dataRoot, dir));
    }
  }

  // Restore state directory (clean first for local-consistent)
  if (fs.existsSync(repoState)) {
    rmDirRecursive(stateRoot);
    ensureDir(stateRoot);
    fileCount += copyDirRecursive(repoState, stateRoot);
  }

  // Restore ~/.agents/skills/ from repo
  if (fs.existsSync(repoAgents)) {
    rmDirRecursive(agentsRoot);
    ensureDir(agentsRoot);
    fileCount += copyDirRecursive(repoAgents, agentsRoot);

    // Restore ~/.agents/.skill-lock.json from repo (lives one level above skills/)
    const agentsParent = path.dirname(agentsRoot);
    const repoLock = path.join(repoAgents, ".skill-lock.json");
    const localLock = path.join(agentsParent, ".skill-lock.json");
    if (copyFileIfExists(repoLock, localLock)) {
      fileCount++;
    }
    // Remove the copy that copyDirRecursive placed inside skills/ (wrong location)
    rmFileIfExists(path.join(agentsRoot, ".skill-lock.json"));
  }

  // restore is internal — no output needed
}

// ── Git setup ────────────────────────────────────────────────────────

function ensureGitConfig(root) {
  // Set local git user for this repo only (don't touch global config)
  const nameResult = git("config user.name", { cwd: root });
  if (!nameResult.ok || !nameResult.out) {
    git('config user.name "OpenCode Sync"', { cwd: root });
  }
  const emailResult = git("config user.email", { cwd: root });
  if (!emailResult.ok || !emailResult.out) {
    git('config user.email "sync@opencode.local"', { cwd: root });
  }
}

function ensureLfs(root) {
  if (skipLfs()) return;
  // Initialize LFS in this repo
  const result = git("lfs install --local", { cwd: root });
  // silently ignore if git-lfs not available
}

function initRepo(root) {
  const remote = getRemoteUrl();

  // Ensure .gitignore and .gitattributes exist before init
  ensureFile(path.join(root, ".gitignore"), DEFAULT_GITIGNORE);
  ensureFile(path.join(root, ".gitattributes"), DEFAULT_GITATTRIBUTES);

  git(`init -b ${BRANCH}`, { cwd: root });
  git(`remote add origin "${remote}"`, { cwd: root });
  ensureGitConfig(root);
  ensureLfs(root);

  // Try to fetch — if remote has content, adopt it
  const fetchResult = git(`fetch origin ${BRANCH}`, { cwd: root });
  if (fetchResult.ok) {
    // Remote has a branch — check if it has commits
    const revResult = git(`rev-parse origin/${BRANCH}`, { cwd: root });
    if (revResult.ok) {
      // Remote has commits — use reset --hard to adopt remote content.
      git(`reset --hard origin/${BRANCH}`, { cwd: root });
      // Set up tracking
      git(`branch --set-upstream-to=origin/${BRANCH} ${BRANCH}`, { cwd: root });
      return "fetched";
    }
  }

  // Remote is empty, no branch, or fetch failed — start fresh
  if (!fetchResult.ok) {
    // fetch failed is not fatal for init — start fresh silently
  }
  return "fresh";
}

/**
 * Ensure repo is ready for operations.
 * Returns the mode ("ready", "fetched", "fresh") or exits on error.
 */
function ensureRepo(root) {
  if (!isGitRepo(root)) {
    const mode = initRepo(root);
    return mode;
  }
  ensureGitConfig(root);
  ensureLfs(root);
  return "ready";
}

// ── Shared push/pull logic ──────────────────────────────────────────

function doPush(root, force, stageInFn, msgPrefix, action, target) {
  // ── Step 1: Ensure repo is initialized
  ensureRepo(root);

  // ── Step 2: Ensure .gitignore / .gitattributes are up to date
  ensureFile(path.join(root, ".gitignore"), DEFAULT_GITIGNORE);
  ensureFile(path.join(root, ".gitattributes"), DEFAULT_GITATTRIBUTES);

  // ── Step 3: Stage files into repo
  stageInFn(root);

  // ── Step 4: Stage everything
  git("add -A", { cwd: root });

  // ── Step 5: Check for changes
  const status = git("status --short", { cwd: root });
  if (!status.ok || !status.out) {
    success("已是最新");
    upToDateBanner(action, target);
    return;
  }

  const lines = status.out.split("\n");
  const added = lines.filter(l => l.startsWith("A ") || l.startsWith("?")).length;
  const modified = lines.filter(l => l.startsWith("M ")).length;
  const deleted = lines.filter(l => l.startsWith("D ")).length;
  const renamed = lines.filter(l => l.startsWith("R ")).length;
  const totalChanges = added + modified + deleted + renamed;

  // Show staging result with stats
  success(`正在从 4 个目录暂存文件...  ${formatStats(added, modified, deleted, renamed)}`);
  // List changed files
  for (const line of lines) {
    const status_char = line.charAt(0);
    const filename = line.slice(3).trim();
    const prefix = status_char === "A" || status_char === "?" ? "+" : status_char === "D" ? "-" : "~";
    console.log(`${c.tn.gray}       ${prefix} ${filename}${c.reset}`);
  }

  // ── Step 6: Commit
  const msg = commitMessage(msgPrefix);
  const commitResult = git(`commit -m "${msg}"`, { cwd: root });
  if (!commitResult.ok) {
    error(`Commit 失败：${(commitResult.err || commitResult.out).split("\n")[0]}`);
    process.exit(1);
  }
  success(`已提交：${totalChanges} 个文件变更`);

  // ── Step 7: Rebase + push
  const remoteRef = git(`rev-parse origin/${BRANCH}`, { cwd: root });
  if (!remoteRef.ok) {
    // First push
    const pushResult = git(`push -u origin ${BRANCH}`, { cwd: root });
    if (pushResult.ok) {
      success("已 Push 到 GitHub repo（首次 Push）");
      completionBanner(action, target);
    } else {
      error(`Push 失败：${(pushResult.err || "").split("\n")[0]}`);
      process.exit(1);
    }
    return;
  }

  // Remote branch exists — rebase then push
  const pullResult = git(`pull --rebase origin ${BRANCH}`, { cwd: root });
  if (pullResult.ok) {
    const pushResult = git(`push origin ${BRANCH}`, { cwd: root });
    if (pushResult.ok) {
      success("已 Push 到 GitHub repo（rebase，无冲突）");
      completionBanner(action, target);
    } else {
      error(`Push 失败：${(pushResult.err || "").split("\n")[0]}`);
      process.exit(1);
    }
    return;
  }

  // Rebase failed — likely conflict
  git("rebase --abort", { cwd: root });

  if (force) {
    const fpResult = git(`push --force-with-lease origin ${BRANCH}`, { cwd: root });
    if (fpResult.ok) {
      success("已强制 Push 到 GitHub repo（force-with-lease）");
      completionBanner(action, target);
    } else {
      error(`强制 Push 失败：${(fpResult.err || "").split("\n")[0]}`);
      process.exit(1);
    }
  } else {
    error("Rebase 冲突，请使用 --force 强制 Push");
    process.exit(1);
  }
}

function doPull(root, force, stageOutFn, label, action, target) {
  // ── Step 1: Ensure repo is initialized
  if (!isGitRepo(root)) {
    const mode = initRepo(root);
    if (mode === "fresh") {
      console.log(`${c.tn.gray}📭 GitHub repo 为空，请先在其他设备上 Push${c.reset}`);
      return;
    }
    // mode === "fetched" — we already have the content
    const files = git("ls-files", { cwd: root });
    const count = files.ok ? files.out.split("\n").filter(Boolean).length : 0;
    stageOutFn(root);
    success(`首次 Pull 完成：📄+${count}`);
    completionBanner(action, target);
    return;
  }

  ensureGitConfig(root);
  ensureLfs(root);

  // ── Step 2: Check for local uncommitted changes → auto-stash
  git("add -A", { cwd: root });
  const status = git("diff --cached --stat", { cwd: root });
  const hasChanges = status.ok && status.out.length > 0;
  let didStash = false;

  if (hasChanges) {
    git("reset HEAD", { cwd: root });

    if (force) {
      git("checkout -- .", { cwd: root });
      git("clean -fd", { cwd: root });
    } else {
      // Auto-stash local changes so pull can proceed
      git("add -A", { cwd: root });
      const stashResult = git("stash push -m \"opencode-sync auto-stash\"", { cwd: root });
      if (stashResult.ok) {
        didStash = true;
      } else {
        error("Stash 失败：" + (stashResult.err || stashResult.out));
        warn("请使用 --force 强制覆盖本地更改");
        process.exit(1);
      }
    }
  }

  // ── Step 3: Fetch
  success("正在从 GitHub Fetch...");
  const fetchResult = git(`fetch origin ${BRANCH}`, { cwd: root });
  if (!fetchResult.ok) {
    error("Fetch 失败：" + fetchResult.err);
    process.exit(1);
  }

  // ── Step 4: Check diff and reset
  const diff = git(`diff --stat HEAD origin/${BRANCH}`, { cwd: root });
  const hasIncoming = diff.ok && diff.out;

  if (hasIncoming) {
    const nameStatus = git(`diff --name-status HEAD origin/${BRANCH}`, { cwd: root });
    const resetResult = git(`reset --hard origin/${BRANCH}`, { cwd: root });
    if (!resetResult.ok) {
      error("Reset 失败：" + resetResult.err);
      process.exit(1);
    }

    if (didStash) {
      const popResult = git("stash pop", { cwd: root });
      if (!popResult.ok) {
        error("Stash 恢复冲突");
        console.error(`   cd "${root}"`);
        console.error("   git stash show → git checkout -- . → git stash drop");
        console.error("   或使用: opencode-pull-force");
        process.exit(1);
      }
    }

    stageOutFn(root);
    const stats = formatDiffStats(nameStatus.ok ? nameStatus.out : "");
    success(`已从 GitHub Pull：${stats}`);
    completionBanner(action, target);
  } else {
    if (didStash) {
      const popResult = git("stash pop", { cwd: root });
      if (!popResult.ok) {
        error("Stash 恢复冲突");
        console.error(`   cd "${root}"`);
        console.error("   git stash show → git checkout -- . → git stash drop");
        console.error("   或使用: opencode-pull-force");
        process.exit(1);
      }
    }

    success("已是最新");
    upToDateBanner(action, target);
  }

  if (label === "config") {
    note("需要重启 OpenCode 生效");
  }
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ── Commands ─────────────────────────────────────────────────────────

function cmdStatus(root) {
  if (!isGitRepo(root)) {
    console.log(`${c.gray}📭 尚未初始化，请先执行 push 或 pull。${c.reset}`);
    return;
  }

  ensureGitConfig(root);
  const lastCommit = git("log --oneline -1", { cwd: root });
  const status = git("status --short", { cwd: root });

  console.log(`${c.cyan}📦 上次同步${c.reset}  ${lastCommit.ok ? lastCommit.out : "暂无提交记录"}`);

  if (status.ok && status.out) {
    const lines = status.out.split("\n");
    console.log(`${c.yellow}📝 检测到 ${lines.length} 项本地改动${c.reset}`);
  } else {
    console.log(`${c.green}✅ 当前干净，没有本地改动${c.reset}`);
  }
}

function cmdPush(root, force, action, target) {
  doPush(root, force, stageConfigDataIn, "sync", action, target);
}

function cmdPull(root, force, action, target) {
  doPull(root, force, stageConfigDataOut, "config", action, target);
}

// ── Main ─────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const command = args[0];
const force = args.includes("--force");
const target = (args.find(a => a.startsWith("--target=")) || "").replace("--target=", "") || "config";
const action = (args.find(a => a.startsWith("--action=")) || "").replace("--action=", "") || command;
const root = getConfigRoot();

if (!fs.existsSync(root)) {
  if (command === "pull") {
    fs.mkdirSync(root, { recursive: true });
  } else {
    console.error(`配置目录不存在：${root}`);
    process.exit(1);
  }
}

switch (command) {
  case "push":
    cmdPush(root, force, action, target);
    break;
  case "pull":
    cmdPull(root, force, action, target);
    break;
  case "status":
    cmdStatus(root);
    break;
  default:
    console.log("用法：node sync-config.js <command> [--force]");
    console.log("");
    console.log("命令：");
    console.log("  push     Push 配置到 GitHub");
    console.log("  pull     从 GitHub Pull 配置");
    console.log("  status   查看同步状态和本地改动");
    console.log("");
    console.log("选项：");
    console.log("  --force   push: rebase 冲突时强制 Push");
    console.log("            pull: 丢弃本地改动（默认自动 stash）");
    console.log("");
    console.log("同步目录：");
    console.log(`  config: ${getConfigRoot()}`);
    console.log(`  data:   ${getDataRoot()}`);
    console.log(`  state:  ${getStateRoot()}`);
    console.log(`  agents: ${getAgentsRoot()}`);
    if (command && command !== "help") process.exit(1);
    break;
}
